name: Request Licence
on:
  workflow_dispatch: {}

jobs:
  requestManualActivationFile:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # Request manual activation file
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          # customImage: 'unityci/editor:ubuntu-2022.3.10f1-android-1.1.2'
          unityVersion: 2022.3.10f1

      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
